### ISSUE TITLE
Traps & Friction Points

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/team#5]
We have consolidated the issues in this epic to an organized notion table. [It is public](https://www.notion.so/prismaio/Nexus-Traps-Friction-Audit-76b56332c78445ef90cd7c582b090edc).

- [ ] https://github.com/prisma-labs/issues/issues/6
- [ ] https://github.com/prisma-labs/nexus/issues/284
- [ ] https://github.com/prisma-labs/nexus/issues/285
- [ ] https://github.com/prisma-labs/nexus/issues/286
- [ ] https://github.com/prisma-labs/nexus/issues/288
- [ ] https://github.com/prisma-labs/nexus/issues/281
- [ ] https://github.com/prisma-labs/nexus-cli/issues/2
- [ ] https://github.com/prisma-labs/nexus-cli/issues/3
- [ ] https://github.com/prisma-labs/nexus-cli/issues/4
- [ ] https://github.com/prisma-labs/nexus-cli/issues/5
- [ ] https://github.com/prisma-labs/nexus-prisma/issues/506
- [ ] https://github.com/prisma-labs/nexus/issues/289
- [ ] https://github.com/prisma-labs/nexus/issues/277
- [ ] https://github.com/prisma-labs/nexus-prisma/issues/472
- [ ] https://github.com/prisma/photonjs/issues/261
- [ ] https://github.com/prisma-labs/nexus/issues/253
- [ ] https://github.com/prisma-labs/nexus/pull/275
- [ ] https://github.com/prisma-labs/nexus-prisma/issues/507
- [ ] https://github.com/prisma-labs/nexus/issues/292
- [ ] https://github.com/prisma-labs/nexus-prisma/issues/479

When this issue is resolved we should be able to mark the following as resolved too:

- [ ] https://github.com/prisma-labs/nexus/issues/77
- [ ] https://github.com/prisma-labs/nexus/issues/146

**Comment by Weakky** [comment]
### 4th draft

*Legend*

- 🔴 Trap
- 🔵 Friction point
- :question: Not sure
- 💡Partial lead/solution

**Runtime typegen**

- 🔴 Runtime error prevents typegen from being re-run, thus making the typechecking desync/broken
  - https://github.com/prisma-labs/nexus/issues/77#issuecomment-470901391
- 🔵 Forgetting to run Server (thus generating new typings) 
  - https://github.com/prisma-labs/nexus/issues/77#issuecomment-478286731
  - 💡Have a separate process always generating typegen
- :large_blue_circle:  No type-checking after cloning a repo
  - :bulb: Use `postInstall` npm hook to run nexus typegen
- 🔵 `ts-node` or `ts-node-dev` need to be used with `--transpile-only` option and typechecking needs to be done via a separate process (commonly handled via VSC tsc process)
  - 💡Abstract that with a `nexus dev` command. One simple solution.

**Type-checking**

- :question: Cryptic type-check error messages (due to conditional typings)
  - https://github.com/prisma-labs/nexus/issues/77#issuecomment-478286731
  - 💡eslint-nexus to provide better error messages

- 🔵: ​ Input properties needs to be inputted in a certain order to make things smooth. (eg: `name` property needs to be define first for the `definition` type-checking to work properly in `objectType`/`inputObjectType` etc)
  - https://github.com/prisma-labs/nexus/issues/77#issuecomment-478286731
  - 💡Breaking change: use `objectType('typeName', { ... })` to force inputting the `name` before the rest 😕
    - Cons: Less composable. We already have composability issues with `t.field`
    - Pros: More consistent with `t.field` & no more typechecking issues.

**Pagination**

- 🔵 `t.relayConnection()` with Photon 
  - https://github.com/prisma-labs/nexus-prisma/issues/423#issuecomment-542188057
  - 💡Have a default implementation of `pageInfo`  as suggested in the issue

**Nexus two phases (walk & build)**

- 🔵 Nexus plugins can't log any specific domain errors without being logged twice (Consequence ⇒ nexus-prisma can't have domain specific errors)
  - https://github.com/prisma-labs/nexus-prisma/issues/472
  - 💡Nexus should pass the `currentPhase` to plugins to make sure to log only once

**Prisma integration**

- 🔵 Two terminals needed  (`prisma2 dev` & `ts-node-dev`)
  - 💡Make `nexus dev` somehow run `prisma2 dev`
- :large_blue_circle: `prisma2 dev` & `ts-node-dev` not working well together (supposedly because some files are read by both processes). (Feedback given by tom during our internal hackathon)

**General**

- :large_blue_circle: Mono-repo (TBD, ask schickling what was the issue)
- :large_blue_circle: Multiple schemas in a same ts project is not possible
  - https://github.com/prisma-labs/nexus/issues/269
  - :bulb: ​`makeSchema` option to customize the global interface name
- :large_blue_circle: Complicated API for `contextType` https://github.com/prisma-labs/nexus/issues/265
  - 💡 A solution is given in the issue
- :large_blue_circle: Cumbersome backing types api when based on generated types ( `typegenAutoConfig.sources`)
  - https://github.com/prisma-labs/nexus/issues/277 (closed, but we probably need to re-open it)
- :large_blue_circle: Deployment/build
  - (docker) https://github.com/prisma-labs/nexus/issues/281
  - (heroku) https://github.com/prisma-labs/nexus-prisma/issues/430 & https://github.com/prisma-labs/nexus-prisma/issues/505
  - (lambda) https://github.com/prisma-labs/nexus/issues/278
  - 💡A  `nexus build --target="heroku|lambda"` command
- :large_blue_circle: Testing
  - https://github.com/prisma-labs/nexus/issues/115
  - 💡 Investigate great patterns + create documentation
- :large_blue_circle: Poor documentation
  - 💡Create better doc 🤷‍♂️

**Comment by jasonkuhrt** [comment]
### Draft 2

## development workflow

### Problems

1. 🔵User needs to manage additional deps to accomplish this workflow (`ts-node-dev`, `ts-node`)

    💡Nexus cli `$ nexus dev|build` can hide them

1. 🔵User needs to remember the right flags to use on `ts-node-dev` (`--transpile-only`, `--tree-kill`) and they need to understand _why_.
    
    [Example: user resisting/insecure about `--transpile-only`](https://prisma.slack.com/archives/CKQTGR6T0/p1571732206174300?thread_ts=1570915353.062700&cid=CKQTGR6T0)

    💡Nexus cli `$ nexus dev|build` can hide this

2. 🔴Generated artifacts in `node_modules` may get pruned
    1. it is not obvious when they will, varies between npm and yarn
    2. when they do there is no feedback for the user they were pruned
    3. when they do there is nothing that automatically re-triggers generation

    💡Facades for photon https://github.com/prisma/photonjs/issues/261  
    💡Facades for nexus typegen https://github.com/prisma-labs/nexus/issues/253  
    💡Nexus typegen hook for plugins so that nexus facade solution can be benefit all plugins  

3. 🔴If the user configures `--types` [compiler option](https://www.typescriptlang.org/docs/handbook/compiler-options.html) their app will no longer automatically use typegen. There will be no feedback about _why_ typegen has stopped working. The user will need to realize that 1) typegen goes into @types and that 2) types compiler option turns that into an opt-in/whitelist.

    💡Nexus cli can use TS compiler api programmatically to inject typegen into `types` option. This will however not help the IDE.  
    💡VSC plugin that takes the above solution into the IDE too?  
    💡New cli sub-command `$ nexus doctor` that looks for problems such as this and tells the user how to fix them.  
    💡VSC plugin that enables doctor at all times so user does not need to remember to run `$ nexus doctor`

4. 🔴There are no docs on workflow patterns and what environment variables have what effects when.

    💡Add a new workflow sub-section under nexus reference docs https://github.com/prisma-labs/nexus/issues/96

5. 🔵User has to maintain at least two terminals, one for prisma dev and one for application dev (ts-node-dev). When they have a t.model or t.crud static error that they don't expect, they need to go through each terminal to find the issue: 1) Did photon fail to build for some reason? 2) Is my app failing to build for some reason (and thus typegen)?

    💡Have `nexus dev` use `@prisma/sdk` to programatically drive prisma dev.

6. 🔵When starting a project it is often not obvious what combination of dependencies are needed to get what one can see working in an example (e.g. prisma 2 alpha, nexus beta, nexus-prisma regular release).

### Maybe Not Problems?

1. Unable to get into a state like described here:

    > 🔴User can modify app code such that nexus/nexus-plugins generation cannot succeed. This is because nexus generation relies on actually running all definition blocks in the source code. Having generation blocked because the app will not run is arguably reasonable if the reason the app will not run is due to a syntax error or some runtime error unrelated to prisma. But it is _not_ reasonable if there is a runtime error from trying to use nexus-prisma in the correct way.

2. Actually `prisma dev` emitting into `node_modules` is triggering `ts-node-dev`, even when `ts-node-dev` is run with `--ignore-watch node_modules`. 

    > 🔵User needs to manually coordinate a nexus generate following a prisma generate  
    For example if user boots up `prisma dev` and `ts-node-dev ...` in two separate terminals, there is a race condition. If `prisma dev` is slower, user will need to trigger a reload of `ts-node-dev` e.g. save on any source file.

    Maybe this is because the dependency graph is being watched as per mentioned in [ts-node-dev readme](https://github.com/whitecolor/ts-node-dev):

    > It restarts target node process when any of required files changes (as standard node-dev) 


## Deployment Workflow

### Problems

1. 🔴Users must apply a specific combination of tools and configurations thereof to successfully build their app "the nexus way".
    1. Have the right env vars in place (`NEXUS_CONFIG='{...}'`)
    1. Use `ts-node`
    1. Pass `ts-node` the right flags (`--transpile-only`)
    1. Pass `ts-node` just the entrypoint to your schema, not server
    1. Then do a normal build `tsc`

    [Example: user not realizing they need special env var to trigger typegen on heroku deploy](https://prisma.slack.com/archives/CKQTGR6T0/p1571681171154400?thread_ts=1571664108.151200&cid=CKQTGR6T0)

    💡We can remove `iv` with https://github.com/prisma-labs/nexus/issues/272, a new config option to exit the process after artifact generation.  
    💡Nexus cli `$ nexus build` can abstract all other steps

2. 🔴Many deployment platforms impose idiosyncratic mechanisms for how users need to structure their application. Often this structuring is not at the code level but project layout level or build pipeline. Because Prisma and Nexus use code generation techniques, users of these tools often fall victum to deployment platforms not expecting this novel-ish workflow. While we could say its not our problem, the bottom line is users experience pain, and theym ay well blame that pain on the technique of generation rather than the deployment tools.

    1. Heroku users must tap into `npm run build` script
    1. Zeit users must tap into `npm run now-build` script
    1. ... `netlify`, `lambda` ...

    `lambda` example: https://github.com/prisma-labs/nexus/issues/278

    💡An example for each platform  
    💡For AWS Lambda, a serverless framework plugin  
    💡For zeit, a custom builder [wrapping the nodejs one](https://zeit.co/docs/builders#official-builders/node-js)

## Other

### Problems

1. 🔵 In all of the above, because it all relies on integration of tools, the workflow that is being put together is not encoded, but rather implicit. That means error messages are never going to be in the domain of the workflow, but siloed and generic to the various tools.  
  
    Another example, again during build, if something goes wrong during the typegen attempt, they will just see a big general ts-node or something error, probably a stack trace, etc. It would be nice if they could see a clear message "Error while building Nexus app. Failied on typegen step. Here was the error: ...".

    💡Nexus cli `$ nexus build|dev` can encode the workflow between tools, introduce domain error messages.

2. 🔵NODE_ENV has effect on "develop mode" even after build. This can lead to unexpected errors. For example a user thought that there was a bug because `require.resolve` used on a ts file for `makeSchema({ contextType })` config would lead to a path to a JS file after build. In turn this would lead to an error in typegen which asserts the file path must be to a `.ts` extenson file. Actually what happened was the user was running e.g. `node dist/index` with not `NODE_ENV=production`. These integration effects are unpredictable to most users and even if they don't always represent a valid combination of states users generally cannot be expected to know every permutation of this. It should just be impossible for them to get into these states in the first place.

    https://github.com/prisma/prisma-examples/pull/867#issuecomment-545400592

    💡Nexus cli `$ nexus build` can inject special code that disables dev features. This would only help TS users since presumably JS users do not need `$ nexus build`.

**Comment by jasonkuhrt** [comment]
@Weakky 

> 🔵 Forgetting to run Server (thus generating new typings)
prisma-labs/nexus#77 (comment)
💡Have a separate process always generating typegen

What does that solution mean/how could it help exactly?

> 🔵 No type-checking after cloning a repo
💡 Use postInstall npm hook to run nexus typegen

The best we could do with that solution is for it to be a pattern we suggest right? Since it would be app-level.

> Cons: Less composable. We already have composability issues with t.field

We could allow the object version too, thus being backwards compatible. And that is nicer for machine use-cases as we identified the other night with `t.field`.

> 🔴 Runtime error prevents typegen from being re-run, thus making the typechecking desync/broken

How could this be fixed, though?

**Comment by Weakky** [comment]
> What does that solution mean/how could it help exactly?

We could, for instance, have a VSC plugin running the typegen in the background, so that it's independent of the runtime.

> The best we could do with that solution is for it to be a pattern we suggest right? Since it would be app-level.

Yes. "Encoding" that pattern in all examples + documenting it might be the best solution here

> We could allow the object version too, thus being backward compatible. And that is nicer for machine use-cases as we identified the other night with t.field.

Still wondering whether it's a good idea to have two APIs to achieve the same thing. Might be confusing for users

> How could this be fixed, though?

I don't think we can, hence why I labeled it as 🔴 (Trap)

**Comment by jasonkuhrt** [comment]
More since here https://github.com/prisma-labs/nexus-prisma/issues/523

**Comment by ujwal-setlur** [comment]
Would love a VSC plugin to generate types
